version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - database:/var/lib/mysql
      - ./turing.sql:/docker-entrypoint-initdb.d/turing.sql
    ports:
      - "6603:3306"
    networks: 
      - webapp
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: turing_api
      MYSQL_USER: turing
      MYSQL_PASSWORD: password
  
  redis:
    image: redis:alpine
    container_name: cache
    networks: 
      - webapp
    ports:
      - "6379:6379"
    volumes:
      - redis_db:/data

  api1:
    build: ./api
    ports:
      - "3000"
    networks: 
      - webapp
    environment: 
      DB_HOST: db
      REDIS_URL: redis://cache
    depends_on:
      - redis
      - db

  api2:
    build: ./api
    ports:
      - "3000"
    networks:
      - webapp
    environment:
      DB_HOST: db
      REDIS_URL: redis://cache
    depends_on:
      - redis
      - db

  loadbalancer:
    build: ./nginx
    networks:
      - webapp
    depends_on:
      - api1
      - api2
    ports:
      - '80:80'

volumes:
  database:
  redis_db:

networks: 
  webapp:
